### ISSUE TITLE
Meta: Finalize New-New Application Process

### ISSUE THREAD

**Issue by carpodaster** [rails-girls-summer-of-code/rgsoc-teams#155]
* [x] @sareg0: Add remaining fields from rails-girls-summer-of-code/organization#89
Pull Request #157 
* [x] @carpodaster: Allow students to lodge a second application (2 is the absolute max)
* [x] @marcgreenstock: Add an application_drafts#index controller action that lists all application drafts of all teams that I am part of (as either student, coach or mentor).  (see #144 + #162)
* [x] @carpodaster: Link application_drafts#index somewhere, but the header nav is quite full already. Ideas?
* [x] @carpodaster: Allow coaches to edit an application
* [x] @marcgreenstock: Send an email to coach / mentor when they are added to a team (see #144)
* [ ] @cypher and @ramonh : Allow mentors to sign-off an application. Q: What happens when the application is modified after it? (see #144) A: Mentors will have a set period after applications close to signoff.
* [x] @ramonh: Add validations for `ApplicationDraft` (see #145 / #130)
* [x] @carpodaster: Create an `Application` record from an `ApplicationDraft` (see #163)
* [x] @lislis: Make editing a team more accessible (ie. form styling), see #152

**Comment by marcgreenstock** [comment]
hey @carpodaster feel free to assign me to the rest of https://github.com/rails-girls-summer-of-code/rgsoc-teams/issues/144. I'm not sure either where to put the link to `application_drafts#index` but I'll go ahead and implement the functionality and leave it up to someone with more UX skills than I do to put the link in.

**Comment by sareg0** [comment]
Hey guys
@ramonh would love to get in on the action of this awesome task list.
@carpodaster he was hoping to take the 'validations' task, but are you mittendrin statt nur dabei on that one?
Is there one the lovely @ramonh could take that won't require too much onboarding?

**Comment by carpodaster** [comment]
@sareg0 @ramonh no, no – I haven't started yet. By all means, go for it :horse_racing: Thanks!

**Comment by ramonh** [comment]
Hiya! Thanks for letting me help. :+1: 

I've downloaded the repo and started familiarizing myself with everything.

**Comment by sareg0** [comment]
AWESOME! Welcome @ramonh will get you on the Slack channel asap.

**Comment by carpodaster** [comment]
@marcgreenstock I've added the link to `application_drafts#index` in cb84f50ae91d1e2de33770b90bfcfc184726c407. It shows a different link depending on who's looking at it. I think it'll do, but if anyone want to beautify it, by all means do :flags:

**Comment by ramonh** [comment]
Hey! So I'm on issue #130 at the moment. Just wondering - We need to add emails as a required field for the user model. Is this correct? 

Thanks in advance!

**Comment by carpodaster** [comment]
Hey @ramonh. I believe the reason why User#email is not required is because users can be added as part of a team just by their github handle. At that stage, we don't know anything about the user yet and can't require an email. It should be a requirement for the `ApplicationDraft` instance though.

**Comment by ramonh** [comment]
Ah! Makes sense. Thank you @carpodaster for your lightning-fast reply.

I'm on it!

**Comment by alicetragedy** [comment]
thank you so much @carpodaster @marcgreenstock @ramonh for all your hard work so far! :heart:

**Comment by ramonh** [comment]
Hey @carpodaster, I noticed that the ApplicationDraft model doesn't have an `email` field, so I'll go ahead and add that too.

**Comment by carpodaster** [comment]
@ramonh can you add method proxies for it? It's stored on the user (as are several other of the application-specific fields). The draft has a reference to the users (`students`) so the validations should just make sure the users have their corresponding attributes set.

**Comment by ramonh** [comment]
Right! I think that makes sense. Will look into it.

**Comment by carpodaster** [comment]
@ramonh cool. And thanks! Don't hesitate do ping me if you have further questions :smile:

**Comment by ramonh** [comment]
No, thank you for bearing with me, @carpodaster! I'm happy to help in any way I can :+1:

**Comment by ramonh** [comment]
I hope that this is what you had in mind! ramonh/rgsoc-teams@0d21551e79d24438e7e85f87f1fecc04a9f87630

**Comment by carpodaster** [comment]
Note: @ramonh and I will pair up on the validations (and probably #163 as well) this Sunday

**Comment by carpodaster** [comment]
Students can now hand in a 2nd application.

**Comment by alicetragedy** [comment]
:tada: that's awesome @carpodaster!

**Comment by sareg0** [comment]
So great! Thank you you two!

**Comment by ramonh** [comment]
Hey @carpodaster, A quick question about the following:
> Q: What happens when the application is modified after it? (see #144) A: Mentors will have a set period after applications close to signoff.

This is what would happen if the application period would close, correct? Does this mean that mentors would be able to edit the application after that?

**Comment by carpodaster** [comment]
Morning @ramonh. When the students submit their application, there is no turning back: they cannot modify it any longer. There is a before action in ApplicationDraftsController (`disallow_modifications_after_submission`) that prevents modification after it has been successfully lodged.

**Comment by ramonh** [comment]
Thank you, @carpodaster! This makes sense to me. What about mentors, then? Can they edit the application?

**Comment by carpodaster** [comment]
No they can't. They can access it read-only, but not modify it before or after it has been submitted.

**Comment by ramonh** [comment]
Perfect,thank you!

**Comment by alicetragedy** [comment]
I guess we can now close this issue, right? :D

**Comment by carpodaster** [comment]
Yes, keeeel it!

**Comment by ramonh** [comment]
🎉👍
