### ISSUE TITLE
Meta: project proposal 2017

### ISSUE THREAD

**Issue by carpodaster** [rails-girls-summer-of-code/rgsoc-teams#551]
* [x] project submission form: "issues and features" will be renamed to "what will the students be working on?" to make it more general
* [x] project submission form: a new text area will be added with the title "requirements" (or something similar) that will list requirements for the project from the point of view of the mentor (e.g. good knowledge of a language, proficiency with CSS, etc..). This can include a little coding challenge or a codecademy track that needs to be completed; more examples of this will be provided in the mentor guide.
* [X] project submission form: add link to guide at the top of the form, to make sure they've read it

**Comment by klappradla** [comment]
Naming is hard, but I think **"requirements"** is a real good choice - perfect fit in my opinion. I went with this name for updating the [guide](https://github.com/rails-girls-summer-of-code/summer-of-code/blob/cbe84e396825e63917f2cc4e9bc00c6e35ef4469/guide/projects.md#how-do-i-submit-my-project) on it, plus used **"tasks and features"**, since *"what will students be working on"* did not quite fit the tone of the guide. However, I don't think there has to be a 1:1 matching between fields and guide, as I see the latter as a more general overview of *"how to 'apply' as a mentor"*, not an explanation of each field (this would go directly into the form).
Just for your information @carpodaster

**Comment by carpodaster** [comment]
Hey @klappradla - thanks for the feedback! PR #553 is up now! :rocket:
